config/routes.rb
Rails.application.routes.draw do

   get 'tweets/:tweet_id/likes' => 'likes#create'
   get 'tweets/:tweet_id/likes/:id' => 'likes#destroy'
  devise_for :users
  resources :users, only: [:show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end
  root 'tweets#index'

  

  patch 'tweets/:id' => 'tweets#update'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user  
    mount_uploader :image, ImageUploader
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tweets, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :liked_tweets, through: :likes, source: :tweet
         validates :name, presence: true
         validates :profile, length: { maximum: 200 }

         def already_liked?(tweet)
          self.likes.exists?(tweet_id: tweet.id)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def index
        @tweets = Tweet.all
        @all_ranks = Tweet.find(Like.group(:tweet_id).order('count(tweet_id) desc').limit(3).pluck(:tweet_id))
        if params[:search] == nil
          @tweets= Tweet.all
        elsif params[:search] == ''
          @tweets= Tweet.all
        else
          @tweets = Tweet.where("topic LIKE ? ",'%' + params[:search] + '%')
        end
    end

    def new
        @tweet = Tweet.new
      end
    
      def create
        tweet = Tweet.new(tweet_params)
        tweet.user_id = current_user.id
        if tweet.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @tweet = Tweet.find(params[:id])
      end

      def edit
        @tweet = Tweet.find(params[:id])
      end

      def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
      end
    
      private
      def tweet_params
        params.require(:tweet).permit(:topic, :genre, :content, :image)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecokatsu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <header>
  <h1>Ecokatsu</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
</body>

</html>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :topic %>
    <%= f.text_field :topic, :size => 100 %>
   <br> 
    <%= f.label :genre %>
    <%= f.text_field :genre, :size => 100 %> 
<br>
    <%= f.label :content %>
    <%= f.text_field :content, :size => 100 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/tweets/index.html.erb
<h1>自分の題名</h1>
<h3>一覧ページ</h3>

<h3>投稿を検索</h3>
 <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<%= link_to "新規投稿へ", new_tweet_path %>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.topic %>
      <%= t.genre %>
      <%= t.content %>
  <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
              <p>いいねを取り消す</p><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
              <p>いいね</p><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>
      <%= link_to "詳細へ", tweet_path(t.id) %>
      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= link_to "削除する", tweet_path(t.id), method: :delete %>
    <% end %>
      <%= link_to t.user.name, user_path(t.user.id) %>
      <%= t.user.email %>
    </div>
  <% end %>
</div>

<% @all_ranks.each.with_index(1) do |tweet, i| %>
  第
  <%= i %>
  位
<%= tweet.topic %>
<% end %>

app/views/tweets/new.html.erb
<h1>(自分の題名)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @tweet do |f| %>


  <div class="field">
    <%= f.label :topic %>
    <%= f.text_field :topic, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>


  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre, :size => 30 %>
  </div>  



  <div class="field">
    <%= f.label :content  %>
    <%= f.text_area :content, :size => "30x2" %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.topic %></p>
  <p><%= @tweet.genre %></p>
  <p><%= @tweet.content %></p>
  <p><%= @tweet.created_at %></p>
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(@tweet), method: :delete do %>
          <p>いいねを取り消す</p><%= @tweet.likes.count %>
        <% end %>
      <% else %>
        <%= link_to tweet_likes_path(@tweet), method: :post do %>
          <p>いいね</p><%= @tweet.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @tweet.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>


<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.topic %>
  <%= t.genre %>
  <%= t.content %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.topic %>
<% end %>
<!-- ここまで-->

<%= link_to "Tweet一覧に戻る", tweets_path %>